using Microsoft.AspNetCore.Components;
using SilentOrbit.BlazorBlogBuilder.Building.FileGeneration;

namespace SilentOrbit.BlazorBlogBuilder.Config;

/// <summary>
/// Metadata for each rendered page.
/// </summary>
public sealed class PageData
{
    public RelUrl URL { get; set; } = null!;
    public string Href => URL.Href;

    /// <summary>
    /// Generated URL until the post is first run.
    /// </summary>
    internal Url? BlogPostRandomURL { get; set; }

    /// <summary>
    /// Unique ID of each post, if set will be used in feeds.
    /// </summary>
    public string? ID { get; set; }

    /// <summary>
    /// Generator for the specific file content
    /// </summary>
    internal FileGeneratorBase? Generator { get; set; }

    public HeaderConfig Head { get; set; } = new HeaderConfig();

    public string? UrlSnippet { get; set; }

    public RelUrl? Image { get; set; }
    public string Title { get; set; } = null!;
    public string SubTitle { get; set; } = null!;

    /// <summary>
    /// Set using a string value, for example: Page.Tags = "tag1, tag2, tag3"
    /// </summary>
    public Tags Tags { get; set; } = new();

    /// <summary>
    /// First published.
    /// Example: Page.Published = "2025-01-01";
    /// </summary>
    public Timestamp? Published { get; set; }

    /// <summary>
    /// Last modified, set using a string value.
    /// Example: Page.Modified = "2025-01-01";
    /// </summary>
    public Timestamp? Modified { get; set; }

    public Author? Author { get; set; }

    public int LikeCount { get; set; }
    public List<Comment> Comments { get; set; } = new();

    public Url? Redirect { get; set; }

    public MarkupString? Summary { get; internal set; }

    /// <summary>
    /// Cache of full content of page.
    /// Not including layout and outer elements.
    /// For use as content in feeds.
    /// </summary>
    public MarkupString? Full { get; internal set; }

    /// <summary>
    /// Include this page in the feed.
    /// Automatically set for 
    /// <see cref="BlogPost"/> and <see cref="Components.Update"/>.
    /// 
    /// Published must be set, otherwise any post with <see cref="InFeed"/> == true will not be generated.
    /// </summary>
    public bool InFeed { get; set; }

    /// <summary>
    /// Include in sitemap
    /// </summary>
    public bool? Sitemap { get; set; }

    /// <summary>
    /// Link to an existing page, 
    /// generated by <see cref="Components.Update"/>
    /// 
    /// True when <see cref="IsUpdateOf"/> is not null, otherwise false.
    /// </summary>
    public bool IsUpdate { get; internal set; }

    /// <summary>
    /// Original page having this update.
    /// </summary>
    internal PageData? IsUpdateOf { get; set; }

    #region Internal Build properties

    /// <summary>
    /// This page will not be generated if set to true;
    /// Page is also considered a draft if <see cref="Published"/> is in the future.
    /// </summary>
    public bool IsDraft { get; set; }

    /// <summary>
    /// Parse post as Markdown.
    /// Requires the page to be rendered using <see cref="Render"/> for example
    /// Overrides <see cref="SiteConfig.Markdown"/> <see cref="MarkdownConfig.BlogPost"/>
    /// </summary>
    public bool? Markdown { get; set; }

    internal bool IsDraftOrNotPublished
    {
        get
        {
            if (SiteBuilder.Instance.Config.BuildConfig.GenerateDraft)
                return false; //Override all below settings
            if (BuildStage == BuildStage.Added)
                return false; //Wait for preprocessing

            if (IsDraft)
                return true;
            //Missing Published only makes BlogPost a draft.
            if (InFeed && Published == null)
                return true;
            if (Published > DateTime.UtcNow ?? false)
                return true;
            return false;
        }
    }

    /// <summary>
    /// Built as a blazor page, as opposed to a static file.
    /// </summary>
    internal bool IsBlazor { get; set; }

    /// <summary>
    /// Set to true to build this page among the last ones.
    /// Used for
    /// - Tag index
    /// - Blog post index
    /// - Page index
    /// </summary>
    public bool BuildLast { get; set; }

    internal BuildStage BuildStage { get; set; } = BuildStage.Added;

    public bool PreScan => BuildStage == BuildStage.PreScan;
    /// <summary>
    /// False during PreScanning
    /// True when the final file is generated.
    /// </summary>
    public bool FinalBuild => BuildStage == BuildStage.FinalBuild;

    public Type? BlazorType { get; internal set; }

    #endregion

    public override string ToString()
    {
        var last = BuildLast ? nameof(BuildLast) : null;
        return $"{Title} ({BlazorType?.Name}, {BuildStage}, {Href}, {last})";
    }
}
