namespace SilentOrbit.StaticOnline.Config;

public class BuildConfig
{
    /// <summary>
    /// The C# type of the Blazor app.
    /// Usually found as the App.razor file.
    ///
    /// Root component type for the Blazor application.
    /// Use <see cref="SiteConfig{App}"/> to specify the Blazor component type.
    /// </summary>
    public Type AppType { get; set; } = null!;

    /// <summary>
    /// Specify explicitly when <see cref="AppType"/> is not a dll next to the wwwroot folder.
    /// </summary>
    public DirPath WwwRoot { get; set; } = null!;

    /// <summary>
    /// Path to the generated static files.
    /// </summary>
    public DirPath Target { get; set; } = null!;

    /// <summary>
    /// Remove attributes generated by Blazor, such as b-az09.
    /// 
    /// Set to false when you are using Blazor Component css.
    /// 
    /// Default: false
    /// </summary>
    public bool StripBlazorAttributes { get; set; }

    /// <summary>
    /// Default Markdown config.
    /// Set individually or use <see cref="MarkdownConfig.All"/> to set all at once.
    /// These default can be overriden by the Markdown property of each page or component.
    /// </summary>
    public MarkdownConfig Markdown { get; set; } = new();

    /// <summary>
    /// Don't generate static files, only run web server.
    /// Default: false; - Will generate files
    /// </summary>
    public bool NoGeneration { get; set; }

    /// <summary>
    /// Generate pages with <see cref="PageData.IsDraft"/> and <see cref="PageData.Published"/> in the future.
    /// Usually only use for testing.
    /// Suggest you add this withing #if DEBUG to not accidentally publish it.
    /// </summary>
    public bool GenerateDraft { get; set; }

    /// <summary>
    /// What to do after the build completes
    /// </summary>
    public AfterBuildConfig AfterBuild { get; set; } = AfterBuildConfig.KeepRunning;
}
