namespace SilentOrbit.StaticOnline.Config;

public class BuildConfig
{
    /// <summary>
    /// The C# type of the Blazor app.
    /// Usually found as the App.razor file.
    ///
    /// Root component type for the Blazor application.
    /// Use <see cref="SiteConfig{App}"/> to specify the Blazor component type.
    /// </summary>
    public Type AppType { get; set; } = null!;

    /// <summary>
    /// Specify explicitly when <see cref="AppType"/> is not a dll next to the wwwroot folder.
    /// </summary>
    public DirPath WwwRoot { get; set; } = null!;

    /// <summary>
    /// Path to the generated static files.
    /// </summary>
    public DirPath Target { get; set; } = null!;

    /// <summary>
    /// Remove attributes generated by Blazor, such as b-az09.
    /// 
    /// Set to false when you are using Blazor Component css.
    /// 
    /// Default: false
    /// </summary>
    public bool StripBlazorAttributes { get; set; }

    /// <summary>
    /// Don't generate static files, only run web server.
    /// Default: false; - Will generate files
    /// </summary>
    public bool NoGeneration { get; set; }

    /// <summary>
    /// Shut down immediately after the site is generated.
    /// Set to false when you want to explote the site during development.
    /// Set to true when running in automatic builds such as GitHub Action.
    /// </summary>
    public bool ExitAfterBuildComplete { get; set; }
}
