namespace SilentOrbit.StaticOnline.Config;

/// <summary>
/// Metadata for each rendered page.
/// </summary>
public sealed class PageData
{
    public Url URL { get; set; } = null!;
    public string Href => URL.Href;

    public Url? Image { get; set; }
    public string Title { get; set; } = null!;
    public string SubTitle { get; set; } = null!;

    /// <summary>
    /// Set using a string value, for example: Page.Tags = "tag1, tag2, tag3"
    /// </summary>
    public Tags Tags { get; set; } = new();

    /// <summary>
    /// First published.
    /// Example: Page.Published = "2025-01-01";
    /// </summary>
    public Timestamp? Published { get; set; }

    /// <summary>
    /// Last modified, set using a string value.
    /// Example: Page.Modified = "2025-01-01";
    /// </summary>
    public Timestamp? Modified { get; set; }


    public Author? Author { get; set; }

    public int LikeCount { get; set; }
    public int CommentCount { get; set; }

    
    public Robots Robots { get; } = new();

    public Url? Redirect { get; set; }

    public string? SummaryHtml { get; internal set; }

    /// <summary>
    /// Include this page in the feed.
    /// Automatically set for 
    /// <see cref="BlogPost"/> and <see cref="Components.Update"/>.
    /// </summary>
    public bool InFeed { get; set; }

    /// <summary>
    /// Link to an existing page, 
    /// generated by <see cref="Components.Update"/>
    /// </summary>
    public bool IsUpdate { get; set; }

    #region Internal Build properties

    /// <summary>
    /// This page will not be generated if set to true;
    /// </summary>
    public bool IsDraft { get; set; }

    /// <summary>
    /// Built as a blazor page, as opposed to a static file.
    /// </summary>
    internal bool IsBlazor { get; set; }

    /// <summary>
    /// Set to true to build this page among the last ones.
    /// Used for
    /// - Tag index
    /// - Blog post index
    /// - Page index
    /// </summary>
    public bool BuildLast { get; set; }

    internal BuildStage BuildStage { get; set; } = BuildStage.Added;

    /// <summary>
    /// False during PreScanning
    /// True when the final file is generated.
    /// </summary>
    public bool FinalBuild { get; set; }

    internal Type? BlazorType { get; set; }

    #endregion

    public override string ToString()
    {
        return $"{Title} ({Href})";
    }
}
