using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SilentOrbit.StaticOnline.Components;

namespace SilentOrbit.StaticOnline.Config;

/// <summary>
/// Metadata for each rendered page.
/// </summary>
public sealed class PageData
{
    public RelUrl URL { get; set; } = null!;
    public string Href => URL.Href;

    /// <summary>
    /// Generated URL until the post is first run.
    /// </summary>
    internal Url? BlogPostRandomURL { get; set; }

    public string? UrlSnippet { get; set; }

    public Url? Image { get; set; }
    public string Title { get; set; } = null!;
    public string SubTitle { get; set; } = null!;

    /// <summary>
    /// Set using a string value, for example: Page.Tags = "tag1, tag2, tag3"
    /// </summary>
    public Tags Tags { get; set; } = new();

    /// <summary>
    /// First published.
    /// Example: Page.Published = "2025-01-01";
    /// </summary>
    public Timestamp? Published { get; set; }

    /// <summary>
    /// Last modified, set using a string value.
    /// Example: Page.Modified = "2025-01-01";
    /// </summary>
    public Timestamp? Modified { get; set; }


    public Author? Author { get; set; }

    public int LikeCount { get; set; }
    public int CommentCount { get; set; }


    public Robots Robots { get; } = new();

    public Url? Redirect { get; set; }

    public MarkupString? Summary { get; internal set; }

    /// <summary>
    /// Include this page in the feed.
    /// Automatically set for 
    /// <see cref="BlogPost"/> and <see cref="Components.Update"/>.
    /// 
    /// Published must be set, otherwise any post with <see cref="InFeed"/> == true will not be generated.
    /// </summary>
    public bool InFeed { get; set; }

    /// <summary>
    /// Link to an existing page, 
    /// generated by <see cref="Components.Update"/>
    /// </summary>
    public bool IsUpdate { get; set; }

    #region Internal Build properties

    /// <summary>
    /// This page will not be generated if set to true;
    /// </summary>
    public bool IsDraft { get; set; }

    /// <summary>
    /// Parse post as Markdown.
    /// Requires the page to be rendered using <see cref="Render"/> for example
    /// Overrides <see cref="SiteConfig.Markdown"/> <see cref="MarkdownConfig.BlogPost"/>
    /// </summary>
    public bool? Markdown { get; set; }

    internal bool IsDraftOrNotPublished
    {
        get
        {
            if (IsDraft)
                return true;
            //Missing Published only makes BlogPost a draft.
            if (InFeed && Published == null)
                return true;
            if (Published > DateTime.UtcNow ?? false)
                return true;
            return false;
        }
    }

    /// <summary>
    /// Built as a blazor page, as opposed to a static file.
    /// </summary>
    internal bool IsBlazor { get; set; }

    /// <summary>
    /// Set to true to build this page among the last ones.
    /// Used for
    /// - Tag index
    /// - Blog post index
    /// - Page index
    /// </summary>
    public bool BuildLast { get; set; }

    internal BuildStage BuildStage { get; set; } = BuildStage.Added;

    /// <summary>
    /// False during PreScanning
    /// True when the final file is generated.
    /// </summary>
    public bool FinalBuild { get; set; }

    internal Type? BlazorType { get; set; }

    /// <summary>
    /// Will render the specific Blazor/razor type.
    /// Will not work on pages that rely on page parameters.
    /// 
    /// Same implementation found in <see cref="PageRender"/>
    /// </summary>
    public RenderFragment Render()
    {
        return RenderTreeBuilder;
    }
    void RenderTreeBuilder(RenderTreeBuilder builder)
    {
        if (BlazorType == null)
            return;

        var useMarkdown =
            (BuildStage == BuildStage.FinalBuild) &&
            (Markdown ?? SiteBuilder.Instance.Config.Markdown.BlogPost);

        if (useMarkdown)
        {
            builder.OpenComponent<Markdown>(0);
            builder.AddAttribute(2, nameof(Components.Markdown.ChildContent), (RenderFragment)((b2) =>
            {
                b2.OpenComponent(3, BlazorType!);
                b2.CloseComponent();
            }));
            builder.CloseComponent();
        }
        else
        {
            builder.OpenComponent(4, BlazorType!);
            builder.CloseComponent();
        }
    }

    #endregion

    public override string ToString()
    {
        var last = BuildLast ? nameof(BuildLast) : null;
        return $"{Title} ({BlazorType?.Name}, {BuildStage}, {Href}, {last})";
    }
}
