namespace SilentOrbit.StaticOnline.Config;

/// <summary>
/// Metadata for each rendered page.
/// </summary>
public sealed class SitePage
{
    public Url URL { get; set; } = null!;
    public string Href => URL.Href;

    public string Title { get; set; } = null!;
    public string SubTitle { get; set; } = null!;

    public Url? Image { get; set; }

    public Author? Author { get; set; }

    public int LikeCount { get; set; }
    
    public int CommentCount { get; set; }

    public Tags Tags { get; set; } = new();

    /// <summary>
    /// Include this page in the feed.
    /// Automatically set for 
    /// <see cref="BlogPost"/> and <see cref="Components.Update"/>.
    /// </summary>
    public bool InFeed { get; set; }

    /// <summary>
    /// Link to an existing page, 
    /// generated by <see cref="Components.Update"/>
    /// </summary>
    public bool IsUpdate { get; set; }

    /// <summary>
    /// Build this page among the last ones.
    /// Used for
    /// - Tag index
    /// - Blog post index
    /// - Page index
    /// 
    /// Can be set manually.
    /// </summary>
    public bool BuildLast { get; set; }

    public Timestamp? Published { get; set; }

    public Timestamp? Modified { get; set; }

    public Robots Robots { get; } = new();

    public Url? Redirect { get; set; }

    public string? SummaryHtml { get; internal set; }

    public BuildStage BuildStage { get; internal set; } = BuildStage.Added;

    #region Internal Build properties

    internal Type? BlazorType { get; set; }

    /// <summary>
    /// This page is not found, used to prevent generation from storing the 404 page.
    /// </summary>
    internal bool NotFound { get; set; }

    /// <summary>
    /// Generated from the request URL
    /// </summary>
    internal bool FromURL { get; set; }

    #endregion

    public override string ToString()
    {
        return $"{Title} ({Href})";
    }
}
