using SilentOrbit.Disk;
using System.Runtime.CompilerServices;

namespace SilentOrbit.StaticOnline.Config;

/// <summary>
/// Metadata for each rendered page.
/// </summary>
public sealed class SitePage
{
    public Url URL { get; set; } = null!;
    public string Href => URL.Href;

    public string Title { get; set; } = null!;
    public string SubTitle { get; set; } = null!;

    public Url? Image { get; set; }

    public Author? Author { get; set; }

    public int LikeCount { get; set; }
    
    public int CommentCount { get; set; }

    public Tags Tags { get; set; } = new();

    /// <summary>
    /// Include this page in the feed.
    /// Automatically set for <see cref="BlogPost"/> and <see cref="Components.Update"/>.
    /// </summary>
    public bool InFeed { get; set; }

    /// <summary>
    /// Link to an existing page, 
    /// generated by <see cref="Components.Update"/>
    /// </summary>
    public bool IsUpdate { get; set; }

    public Type? BlazorType { get; set; }

    /// <summary>
    /// Build this page among the last ones.
    /// Used for
    /// - Tag index
    /// - Blog post index
    /// - Page index
    /// </summary>
    public bool BuildLast { get; set; }

    /// <summary>
    /// This page is not found, used to prevent generation from storing the 404 page.
    /// </summary>
    internal bool NotFound { get; set; }

    public Timestamp? Published { get; set; }

    public Timestamp? Modified { get; set; }

    public Robots Robots { get; } = new();

    public Url? Redirect { get; set; }

    public string? SummaryHtml { get; internal set; }

    /// <summary>
    /// Generated from the request URL
    /// </summary>
    internal bool FromURL { get; set; }

    public BuildStage BuildStage { get; internal set; } = BuildStage.Added;

#if DEBUG
    [Obsolete("Will not work in a checkedout repo")]
    public void SetModified([CallerFilePath] string callerPath = null!)
    {
        if (callerPath == null)
        {
            Debug.Fail("Caller path missing");
            return;
        }

        var file = new FilePath(callerPath);
        if (file.Exists() == false)
        {
            Debug.Fail("File not found " + file);
            return;
        }

        Modified = file.FileInfo.LastWriteTimeUtc;
    }
#endif

    public override string ToString()
    {
        return $"{Title} ({Href})";
    }
}
